import "./content.css"

const ContentPage = ({isOpen, onClose, children}) => {
    return (
        <div >
            {isOpen ? (
                <div className="ContentPageContainer">
                    <button className="CloseContent" onClick={onClose}>X</button>
                    <div className="ContentContainer">
                        <div className="TextContainer">
                            <div className="ContentTitle"><h2>LOREM IPSUM DOLOR SIT</h2></div>
                            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae placerat dolor, suscipit sollicitudin ipsum. Donec tempor sit amet metus nec fermentum. Vivamus at aliquet nibh, a convallis justo. Vivamus sit amet dapibus arcu, eu lobortis metus. Fusce vestibulum facilisis dolor, dictum finibus purus aliquet eu. Mauris vitae euismod arcu, vitae semper ligula. Duis in vehicula turpis. Phasellus dapibus libero ut libero vestibulum, sed molestie tellus feugiat. Nunc et luctus ante, ut ultrices augue. Proin vel ipsum molestie odio congue posuere.
                            </p>
                        </div>
                        {children}
                    </div>
                </div>
            ) : null}
        </div>
    )
}

export default ContentPage